"""Regenerate modules/_manifest.py — an explicit list of technique modules.

PyInstaller-frozen apps can't reliably discover submodules with pkgutil, so the
scanner also imports every module listed in the manifest. Run this whenever you
add/remove a technique module (the build script does this automatically):

    python tools/gen_manifest.py
"""
from __future__ import annotations

import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
MODULES_DIR = os.path.join(ROOT, "modules")


def discover() -> list[str]:
    names: list[str] = []
    for sub in sorted(os.listdir(MODULES_DIR)):
        subdir = os.path.join(MODULES_DIR, sub)
        if not os.path.isdir(subdir) or sub.startswith("_") or sub == "__pycache__":
            continue
        for fn in sorted(os.listdir(subdir)):
            if fn.endswith(".py") and fn not in ("__init__.py", "base.py"):
                names.append(f"modules.{sub}.{fn[:-3]}")
    return names


def main() -> None:
    names = discover()
    lines = [
        '"""Auto-generated by tools/gen_manifest.py — do not edit by hand."""',
        "",
        "MODULE_MODULES = [",
    ]
    lines += [f'    "{n}",' for n in names]
    lines += ["]", ""]
    out = os.path.join(MODULES_DIR, "_manifest.py")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print(f"Wrote {out} with {len(names)} modules.")


if __name__ == "__main__":
    main()
